name = "run"
version = "0.0.1"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
benchmark = { path = "../../lib/maelg/benchmark" }
